In [1]:
import pandas as pd

# Baseline model

In [5]:
phase4=pd.read_csv('../datasets/baseline_model_comparison.csv')

In [6]:
phase4

,Model,MAE,MSE,RMSE,MAPE,R²,Forecast Bias
0,Naive Forecast,0.032438,0.001772,0.042093,7.554568,0.953687,-0.000006
1,Moving Average,0.110163,0.018600,0.136381,27.511081,0.513833,-0.000211
2,Previous-Day Forecast,0.065635,0.008225,0.090694,14.612019,0.785004,-0.000367
3,Previous-Week Forecast,0.102124,0.019438,0.139421,22.065621,0.492505,-0.001741

# best model for one features

In [9]:
phase5_comparison = pd.DataFrame({
    'Sequence Length': [168,168,168,168],
    'Model': ['Bi-LSTM','GRU','LSTM','Basic RNN'],
    'MAE': [
        1375.059203,
        1430.083717,
        1469.947544,
        1525.766367
    ],
    'MSE': [
        3.694165e+06,
        3.936318e+06,
        4.021210e+06,
        4.405980e+06
    ],
    'RMSE': [
        1922.021009,
        1984.015685,
        2005.295450,
        2099.042521
    ],
    'MAPE': [
        4.399766,
        4.567817,
        4.737814,
        4.969714
    ],
    'R²': [
        0.907469,
        0.901404,
        0.899278,
        0.889640
    ],
    'Bias': [
        197.749659,
        -6.780432,
        293.431907,
        315.708250
    ]
})

phase5_comparison

,Sequence Length,Model,MAE,MSE,RMSE,MAPE,R²,Bias
0,168,Bi-LSTM,1375.059203,3694165.0,1922.021009,4.399766,0.907469,197.749659
1,168,GRU,1430.083717,3936318.0,1984.015685,4.567817,0.901404,-6.780432
2,168,LSTM,1469.947544,4021210.0,2005.295450,4.737814,0.899278,293.431907
3,168,Basic RNN,1525.766367,4405980.0,2099.042521,4.969714,0.889640,315.708250

# Model Improvement using 14 feautures

In [8]:
phase6_comparison = pd.DataFrame({

    'Sequence Length': [168,168,168,168],
    'Model': ['RNN + LR Scheduler','LSTM + EarlyStopping','GRU + Two Layers','Baseline Bi-LSTM'],
    'MAE': [
        1294.145288,
        1296.983477,
        1311.694007,
        1276.378402
    ],
    'MSE': [
        3.444886e+06,
        3.311891e+06,
        3.453777e+06,
        3.259922e+06
    ],
    'RMSE': [
        1856.040518,
        1819.860119,
        1858.434145,
        1805.525407
    ],
    'MAPE': [
        4.119253,
        4.114061,
        4.179087,
        4.045682
    ],
    'R²': [
        0.913713,
        0.917045,
        0.913491,
        0.918346
    ],
    'Bias': [
        91.140946,
        -9.866167,
        224.022202,
        55.596732
    ]
})

phase6_comparison

,Sequence Length,Model,MAE,MSE,RMSE,MAPE,R²,Bias
0,168,RNN + LR Scheduler,1294.145288,3444886.0,1856.040518,4.119253,0.913713,91.140946
1,168,LSTM + EarlyStopping,1296.983477,3311891.0,1819.860119,4.114061,0.917045,-9.866167
2,168,GRU + Two Layers,1311.694007,3453777.0,1858.434145,4.179087,0.913491,224.022202
3,168,Baseline Bi-LSTM,1276.378402,3259922.0,1805.525407,4.045682,0.918346,55.596732

In [11]:
import os
os.getcwd()

'/home/aximsoft/PycharmProjects/Weekend-Task/electricity-forecasting/notebooks'

In [12]:
phase4.to_csv('../datasets/baseline_model_comparison.csv', index=False)
phase5_comparison.to_csv('../datasets/phase5_comparison.csv', index=False)
phase6_comparison.to_csv('../datasets/phase6_comparison.csv', index=False)