### Text Preprocessing

#### import libraries

In [40]:
import pandas as pd
import numpy as np
import re

from nltk.corpus import stopwords
import nltk

from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [41]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/aximsoft/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

### Load the datasets

In [42]:
data=pd.read_csv('../dataset/IMDB Dataset.csv')

### Missing Vlaues

In [43]:
print(data.isnull().sum())

review       0
sentiment    0
dtype: int64

##### No missing values in the datasets

### Handle Duplicates

In [44]:
print("Duplicate rows:", data.duplicated().sum())

Duplicate rows: 418

In [45]:
duplicates=data[data['review'].duplicated(keep=False)]
duplicates.head(20)

                                                 review sentiment
42    Of all the films I have seen, this one, The Ra...  negative
84    We brought this film as a joke for a friend, a...  negative
140   Before I begin, let me get something off my ch...  negative
219   Ed Wood rides again. The fact that this movie ...  negative
245   I have seen this film at least 100 times and I...  positive
480   From director Barbet Schroder (Reversal of For...  negative
513   The story and the show were good, but it was r...  negative
636   I rented this thinking it would be pretty good...  negative
638   This movie has everything typical horror movie...  positive
701   I Enjoyed Watching This Well Acted Movie Very ...  positive
717   I want very much to believe that the above quo...  negative
744   Sigh. I'm baffled when I see a short like this...  negative
1078  I thought Rachel York was fantastic as "Lucy."...  positive
1196  I've tried to reconcile why so many bad review...  positive
1215  This movie has made me upset! When I think of ...  negative
1233  Beautiful film, pure Cassavetes style. Gena Ro...  positive
1314  There are plenty of comments already posted sa...  negative
1501  Yes, bad acting isn't only one thing to mentio...  negative
1553  French Cinema sucks! Down with all these psych...  negative
1748  My favourite police series of all time turns t...  positive

In [46]:
duplicates["sentiment"].value_counts()

sentiment
negative    598
positive    226
Name: count, dtype: int64

In [47]:
print("Before removing duplicates:")
print(data["sentiment"].value_counts())

print(
    data["sentiment"].value_counts(normalize=True) * 100
)

Before removing duplicates:
sentiment
positive    25000
negative    25000
Name: count, dtype: int64
sentiment
positive    50.0
negative    50.0
Name: proportion, dtype: float64

In [48]:
df_no_duplicates = data.drop_duplicates()

In [49]:
print("After removing duplicates:")
print(df_no_duplicates["sentiment"].value_counts())

print(
    df_no_duplicates["sentiment"].value_counts(normalize=True) * 100
)

After removing duplicates:
sentiment
positive    24884
negative    24698
Name: count, dtype: int64
sentiment
positive    50.187568
negative    49.812432
Name: proportion, dtype: float64

In [50]:
data = data.drop_duplicates(subset=["review"]).copy()

In [51]:
print("Dataset shape:", data.shape)
print("Duplicates:", data["review"].duplicated().sum())

Dataset shape: (49582, 2)
Duplicates: 0

### Convert sentiment into numbers

In [52]:
data["label"] = data["sentiment"].map({"negative": 0,"positive":1})

In [53]:
data[["sentiment", "label"]].head()

  sentiment  label
0  positive      1
1  positive      1
2  positive      1
3  negative      0
4  positive      1

### Create the text preprocessing function

In [54]:
# Get English stopwords
stop_words = set(stopwords.words("english"))
# Keep important negation words for sentiment analysis
negation_words =  {
    "no",
    "not",
    "nor",
    "never",
    "neither",
    "none",
    "nobody",
    "nothing",
    "nowhere",
    "hardly",
    "scarcely",
    "barely",
    "isn't",
    "wasn't",
    "didn't",
    "don't",
    "can't",
    "couldn't",
    "won't"
}
# Remove negation words from the stopword list
stop_words = stop_words - negation_words

In [55]:
def preprocess_text(text):
    # 1. Convert to lowercase
    text = text.lower()
    # 2. Remove HTML tags
    text = re.sub(r"<.*?>", " ", text)
    # 3. Remove punctuation and unnecessary characters
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    # 4. Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()
    # 5. Remove stopwords
    #    but keep: not, no, nor, never
    words = text.split()
    words = [
        word for word in words
        if word not in stop_words
    ]
    # 6. Join words back together
    text = " ".join(words)
    return text

### Test the preprocessing function

In [56]:
sample_review = data["review"].iloc[0]
print("Original:")
print(sample_review)
print("\nPreprocessed:")
print(preprocess_text(sample_review))

Original:
One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

Preprocessed:
one reviewers mentioned watching oz episode hooked right exactly happened first thing struck oz brutality unflinching scenes violence set right word go trust not show faint hearted timid show pulls no punches regards drugs sex violence hardcore classic use word called oz nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy not high agenda em city home many aryans muslims gangstas latinos christians italians irish scuffles death stares dodgy dealings shady agreements never far away would say main appeal show due fact goes shows dare forget pretty pictures painted mainstream audiences forget charm forget romance oz mess around first episode ever saw struck nasty surreal say ready watched developed taste oz got accustomed high levels graphic violence not violence injustice crooked guards sold nickel inmates kill order get away well mannered middle class inmates turned prison bitches due lack street skills prison experience watching oz may become comfortable uncomfortable viewing thats get touch darker side

### Apply preprocessing to all reviews

In [57]:
data["cleaned_review"] = data["review"].apply(preprocess_text)

In [58]:
data[["review","cleaned_review"]].head()

,review,cleaned_review
0,One of the other reviewers has mentioned that ...,one reviewers mentioned watching oz episode ho...
1,A wonderful little production. <br /><br />The...,wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,basically family little boy jake thinks zombie...
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter mattei love time money visually stunnin...

In [59]:
data.head()

,review,sentiment,label,cleaned_review
0,One of the other reviewers has mentioned that ...,positive,1,one reviewers mentioned watching oz episode ho...
1,A wonderful little production. <br /><br />The...,positive,1,wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,positive,1,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,negative,0,basically family little boy jake thinks zombie...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1,petter mattei love time money visually stunnin...

#### Seperate X and y

In [60]:
X = data["cleaned_review"]
y = data["label"]

#### Create Train, Validation and Test datasets

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.15,random_state=42,stratify=y)

In [62]:
X_train, X_val, y_train, y_val = train_test_split(X_train,y_train,test_size=0.1765,random_state=42,stratify=y_train)

In [63]:
print("Training:", len(X_train))
print("Validation:", len(X_val))
print("Testing:", len(X_test))

Training: 34705
Validation: 7439
Testing: 7438

### Tokenization

In [64]:
vocab_size = 20000
tokenizer = Tokenizer(num_words=vocab_size,oov_token="<OOV>")

In [65]:
tokenizer.fit_on_texts(X_train)

### Convert text into sequences

In [66]:
#Training
X_train_sequences = tokenizer.texts_to_sequences(X_train)
#Validation
X_val_sequences = tokenizer.texts_to_sequences(X_val)
#Testing
X_test_sequences = tokenizer.texts_to_sequences(X_test)

In [67]:
print(X_train.iloc[0])
print(X_train_sequences[0])

not much say one except probably worst early spate zombie movies may get watch another one revolt zombies month star john carradine intention building army service third reich not seen much james baskett uncle remus song south plays leader also serves carradine manservant black comic mantan moreland reprises fraidy cat chauffeur role king zombies exotically named madame sul te wan carradine housekeeper unfortunately carradine supreme achievement zombification wife brings sorts trouble not relatives turn remote abode lab inquire sudden death means fake funeral service actually proves disobedient indignant eventually persuading fellow zombies rise master also involved cowboy star bob steele still best known bit howard hawks big sleep plays u secret agent posing nazi posing sheriff thankfully director sekely would much better luck next genre effort day triffids
[4, 16, 51, 5, 432, 130, 144, 291, 1, 826, 27, 96, 18, 31, 64, 5, 7914, 1119, 3151, 206, 193, 4363, 3441, 1181, 1078, 2168, 743, 18546, 4, 34, 16, 474, 1, 1624, 1, 441, 1110, 187, 1616, 21, 2389, 4363, 1, 204, 575, 1, 1, 14458, 1, 1031, 13719, 107, 552, 1119, 1, 634, 12228, 1, 12457, 7291, 4363, 9450, 351, 4363, 5739, 3343, 1, 203, 815, 2422, 932, 4, 4582, 342, 2757, 1, 3521, 1, 2028, 213, 686, 994, 3686, 2168, 66, 1486, 1, 1, 716, 1, 1477, 1119, 2045, 983, 21, 454, 2722, 206, 1678, 7819, 50, 41, 416, 120, 1591, 11470, 89, 1503, 187, 971, 897, 1294, 6254, 2455, 6254, 1961, 2288, 62, 1, 11, 16, 47, 1882, 245, 374, 635, 142, 1]

### Padding

In [68]:
max_length = 200

In [69]:
#Train data
X_train_padded = pad_sequences(X_train_sequences,maxlen=max_length,padding="post",truncating="post")
#Validation
X_val_padded = pad_sequences(X_val_sequences,maxlen=max_length,padding="post",truncating="post")
#Test
X_test_padded = pad_sequences(X_test_sequences,maxlen=max_length,padding="post",truncating="post")

In [70]:
print("Training shape:", X_train_padded.shape)
print("Validation shape:", X_val_padded.shape)
print("Testing shape:", X_test_padded.shape)

Training shape: (34705, 200)
Validation shape: (7439, 200)
Testing shape: (7438, 200)

### Check a padded sequence

In [71]:
print(X_train_padded[0])

[    4    16    51     5   432   130   144   291     1   826    27    96
    18    31    64     5  7914  1119  3151   206   193  4363  3441  1181
  1078  2168   743 18546     4    34    16   474     1  1624     1   441
  1110   187  1616    21  2389  4363     1   204   575     1     1 14458
     1  1031 13719   107   552  1119     1   634 12228     1 12457  7291
  4363  9450   351  4363  5739  3343     1   203   815  2422   932     4
  4582   342  2757     1  3521     1  2028   213   686   994  3686  2168
    66  1486     1     1   716     1  1477  1119  2045   983    21   454
  2722   206  1678  7819    50    41   416   120  1591 11470    89  1503
   187   971   897  1294  6254  2455  6254  1961  2288    62     1    11
    16    47  1882   245   374   635   142     1     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0]

In [72]:
tokenizer.word_index

{'<OOV>': 1,
 'movie': 2,
 'film': 3,
 'not': 4,
 'one': 5,
 'like': 6,
 'good': 7,
 'no': 8,
 'time': 9,
 'even': 10,
 'would': 11,
 'story': 12,
 'really': 13,
 'see': 14,
 'well': 15,
 'much': 16,
 'bad': 17,
 'get': 18,
 'great': 19,
 'people': 20,
 'also': 21,
 'first': 22,
 'made': 23,
 'make': 24,
 'could': 25,
 'way': 26,
 'movies': 27,
 'think': 28,
 'characters': 29,
 'character': 30,
 'watch': 31,
 'films': 32,
 'two': 33,
 'seen': 34,
 'many': 35,
 'love': 36,
 'acting': 37,
 'plot': 38,
 'never': 39,
 'life': 40,
 'best': 41,
 'show': 42,
 'know': 43,
 'little': 44,
 'ever': 45,
 'man': 46,
 'better': 47,
 'end': 48,
 'scene': 49,
 'still': 50,
 'say': 51,
 'scenes': 52,
 'something': 53,
 'go': 54,
 'back': 55,
 'real': 56,
 'thing': 57,
 'watching': 58,
 'actors': 59,
 'years': 60,
 'though': 61,
 'director': 62,
 'funny': 63,
 'another': 64,
 'old': 65,
 'actually': 66,
 'work': 67,
 'makes': 68,
 'nothing': 69,
 'look': 70,
 'going': 71,
 'find': 72,
 'lot': 73,
 'new': 74,
 'every': 75,
 'part': 76,
 'cast': 77,
 'world': 78,
 'things': 79,
 'quite': 80,
 'us': 81,
 'want': 82,
 'horror': 83,
 'pretty': 84,
 'around': 85,
 'seems': 86,
 'however': 87,
 'got': 88,
 'big': 89,
 'enough': 90,
 'take': 91,
 'young': 92,
 'fact': 93,
 'thought': 94,
 'long': 95,
 'may': 96,
 'give': 97,
 'comedy': 98,
 'must': 99,
 'series': 100,
 'action': 101,
 'right': 102,
 'music': 103,
 'original': 104,
 'without': 105,
 'guy': 106,
 'role': 107,
 'saw': 108,
 'come': 109,
 'gets': 110,
 'almost': 111,
 'times': 112,
 'always': 113,
 'point': 114,
 'whole': 115,
 'least': 116,
 'interesting': 117,
 'done': 118,
 'far': 119,
 'bit': 120,
 'script': 121,
 'family': 122,
 'might': 123,
 'making': 124,
 'minutes': 125,
 'feel': 126,
 'anything': 127,
 'since': 128,
 'tv': 129,
 'probably': 130,
 'last': 131,
 'performance': 132,
 'girl': 133,
 'away': 134,
 'yet': 135,
 'kind': 136,
 'rather': 137,
 'fun': 138,
 'anyone': 139,
 'woman': 140,
 'sure': 141,
 'day': 142,
 'played': 143,
 'worst': 144,
 'hard': 145,
 'found': 146,
 'looking': 147,
 'screen': 148,
 'believe': 149,
 'although': 150,
 'trying': 151,
 'especially': 152,
 'book': 153,
 'dvd': 154,
 'put': 155,
 'set': 156,
 'comes': 157,
 'course': 158,
 'goes': 159,
 'three': 160,
 'everything': 161,
 'ending': 162,
 'worth': 163,
 'place': 164,
 'different': 165,
 'maybe': 166,
 'actor': 167,
 'let': 168,
 'main': 169,
 'shows': 170,
 'american': 171,
 'someone': 172,
 'effects': 173,
 'sense': 174,
 'play': 175,
 'reason': 176,
 'true': 177,
 'money': 178,
 'job': 179,
 'watched': 180,
 'everyone': 181,
 'year': 182,
 'together': 183,
 'high': 184,
 'audience': 185,
 'looks': 186,
 'plays': 187,
 'war': 188,
 'instead': 189,
 'special': 190,
 'later': 191,
 'said': 192,
 'john': 193,
 'takes': 194,
 'half': 195,
 'seeing': 196,
 'night': 197,
 'seem': 198,
 'beautiful': 199,
 'version': 200,
 'house': 201,
 'left': 202,
 'wife': 203,
 'black': 204,
 'shot': 205,
 'star': 206,
 'idea': 207,
 'excellent': 208,
 'father': 209,
 'else': 210,
 'fan': 211,
 'mind': 212,
 'death': 213,
 'budget': 214,
 'used': 215,
 'simply': 216,
 'poor': 217,
 'second': 218,
 'nice': 219,
 'read': 220,
 'short': 221,
 'completely': 222,
 'less': 223,
 'top': 224,
 'home': 225,
 'along': 226,
 'men': 227,
 'dead': 228,
 'line': 229,
 'production': 230,
 'boring': 231,
 'camera': 232,
 'hollywood': 233,
 'enjoy': 234,
 'need': 235,
 'help': 236,
 'either': 237,
 'kids': 238,
 'try': 239,
 'women': 240,
 'given': 241,
 'classic': 242,
 'full': 243,
 'friends': 244,
 'next': 245,
 'wrong': 246,
 'school': 247,
 'rest': 248,
 'use': 249,
 'low': 250,
 'truly': 251,
 'stupid': 252,
 'video': 253,
 'start': 254,
 'awful': 255,
 'performances': 256,
 'couple': 257,
 'sex': 258,
 'tell': 259,
 'understand': 260,
 'came': 261,
 'mean': 262,
 'recommend': 263,
 'getting': 264,
 'remember': 265,
 'terrible': 266,
 'perhaps': 267,
 'keep': 268,
 'mother': 269,
 'face': 270,
 'style': 271,
 'name': 272,
 'moments': 273,
 'person': 274,
 'human': 275,
 'episode': 276,
 'wonderful': 277,
 'often': 278,
 'written': 279,
 'others': 280,
 'boy': 281,
 'playing': 282,
 'perfect': 283,
 'piece': 284,
 'definitely': 285,
 'children': 286,
 'head': 287,
 'stars': 288,
 'gives': 289,
 'small': 290,
 'early': 291,
 'dialogue': 292,
 'lines': 293,
 'lost': 294,
 'oh': 295,
 'finally': 296,
 'went': 297,
 'entertaining': 298,
 'sort': 299,
 'absolutely': 300,
 'yes': 301,
 'live': 302,
 'title': 303,
 'case': 304,
 'certainly': 305,
 'cinema': 306,
 'guys': 307,
 'liked': 308,
 'picture': 309,
 'worse': 310,
 'laugh': 311,
 'friend': 312,
 'hope': 313,
 'several': 314,
 'loved': 315,
 'become': 316,
 'felt': 317,
 'called': 318,
 'white': 319,
 'supposed': 320,
 'mr': 321,
 'drama': 322,
 'entire': 323,
 'based': 324,
 'sound': 325,
 'fans': 326,
 'game': 327,
 'totally': 328,
 'problem': 329,
 'overall': 330,
 'dark': 331,
 'beginning': 332,
 'care': 333,
 'waste': 334,
 'guess': 335,
 'b': 336,
 'evil': 337,
 'despite': 338,
 'example': 339,
 'lead': 340,
 'throughout': 341,
 'turn': 342,
 'able': 343,
 'becomes': 344,
 'seemed': 345,
 'final': 346,
 'humor': 347,
 'lives': 348,
 'wanted': 349,
 'direction': 350,
 'unfortunately': 351,
 'quality': 352,
 'history': 353,
 'already': 354,
 'days': 355,
 'killer': 356,
 'flick': 357,
 'michael': 358,
 'art': 359,
 'amazing': 360,
 'run': 361,
 'son': 362,
 'fine': 363,
 'wants': 364,
 'heart': 365,
 'writing': 366,
 'behind': 367,
 'child': 368,
 'close': 369,
 'etc': 370,
 'side': 371,
 'horrible': 372,
 'works': 373,
 'genre': 374,
 'girls': 375,
 'god': 376,
 'kill': 377,
 'turns': 378,
 'today': 379,
 'past': 380,
 'act': 381,
 'gave': 382,
 'eyes': 383,
 'directed': 384,
 'hour': 385,
 'matter': 386,
 'stuff': 387,
 'parts': 388,
 'car': 389,
 'late': 390,
 'viewer': 391,
 'hand': 392,
 'enjoyed': 393,
 'decent': 394,
 'kid': 395,
 'obviously': 396,
 'brilliant': 397,
 'sometimes': 398,
 'tries': 399,
 'soon': 400,
 'expect': 401,
 'town': 402,
 'city': 403,
 'killed': 404,
 'favorite': 405,
 'type': 406,
 'starts': 407,
 'stop': 408,
 'actress': 409,
 'blood': 410,
 'highly': 411,
 'thinking': 412,
 'says': 413,
 'self': 414,
 'feeling': 415,
 'known': 416,
 'group': 417,
 'voice': 418,
 'daughter': 419,
 'writer': 420,
 'anyway': 421,
 'took': 422,
 'happens': 423,
 'experience': 424,
 'fight': 425,
 'heard': 426,
 'hero': 427,
 'moment': 428,
 'leave': 429,
 'strong': 430,
 'coming': 431,
 'except': 432,
 'slow': 433,
 'hit': 434,
 'roles': 435,
 'told': 436,
 'score': 437,
 'brother': 438,
 'stories': 439,
 'save': 440,
 'song': 441,
 'including': 442,
 'hell': 443,
 'violence': 444,
 'happen': 445,
 'hilarious': 446,
 'particularly': 447,
 'crap': 448,
 'chance': 449,
 'looked': 450,
 'cannot': 451,
 'serious': 452,
 'murder': 453,
 'involved': 454,
 'ok': 455,
 'alone': 456,
 'lack': 457,
 'simple': 458,
 'extremely': 459,
 'david': 460,
 'police': 461,
 'cut': 462,
 'cool': 463,
 'taken': 464,
 'seriously': 465,
 'ago': 466,
 'obvious': 467,
 'wonder': 468,
 'complete': 469,
 'husband': 470,
 'gore': 471,
 'attempt': 472,
 'please': 473,
 'james': 474,
 'robert': 475,
 'exactly': 476,
 'across': 477,
 'living': 478,
 'released': 479,
 'shown': 480,
 'happened': 481,
 'age': 482,
 'none': 483,
 'opening': 484,
 'interest': 485,
 'english': 486,
 'number': 487,
 'jokes': 488,
 'saying': 489,
 'reality': 490,
 'cinematography': 491,
 'whose': 492,
 'relationship': 493,
 'hours': 494,
 'talent': 495,
 'order': 496,
 'running': 497,
 'usually': 498,
 'change': 499,
 'career': 500,
 'shots': 501,
 'country': 502,
 'sad': 503,
 'word': 504,
 'huge': 505,
 'view': 506,
 'possible': 507,
 'novel': 508,
 'four': 509,
 'silly': 510,
 'ridiculous': 511,
 'annoying': 512,
 'power': 513,
 'level': 514,
 'words': 515,
 'light': 516,
 'ends': 517,
 'important': 518,
 'attention': 519,
 'female': 520,
 'taking': 521,
 'wish': 522,
 'mostly': 523,
 'beyond': 524,
 'body': 525,
 'jack': 526,
 'turned': 527,
 'talking': 528,
 'usual': 529,
 'musical': 530,
 'room': 531,
 'middle': 532,
 'documentary': 533,
 'ones': 534,
 'somewhat': 535,
 'call': 536,
 'basically': 537,
 'strange': 538,
 'started': 539,
 'scary': 540,
 'knows': 541,
 'modern': 542,
 'major': 543,
 'happy': 544,
 'clich': 545,
 'apparently': 546,
 'rating': 547,
 'knew': 548,
 'episodes': 549,
 'team': 550,
 'single': 551,
 'king': 552,
 'television': 553,
 'due': 554,
 'non': 555,
 'upon': 556,
 'opinion': 557,
 'french': 558,
 'disappointed': 559,
 'events': 560,
 'finds': 561,
 'cheap': 562,
 'miss': 563,
 'earth': 564,
 'problems': 565,
 'local': 566,
 'enjoyable': 567,
 'five': 568,
 'british': 569,
 'straight': 570,
 'songs': 571,
 'clearly': 572,
 'thriller': 573,
 'easily': 574,
 'comic': 575,
 'future': 576,
 'similar': 577,
 'talk': 578,
 'eye': 579,
 'add': 580,
 'moving': 581,
 'space': 582,
 'predictable': 583,
 'class': 584,
 'sequence': 585,
 'die': 586,
 'review': 587,
 'near': 588,
 'tells': 589,
 'filmed': 590,
 'george': 591,
 'sets': 592,
 'ten': 593,
 'fast': 594,
 'soundtrack': 595,
 'e': 596,
 'falls': 597,
 'lots': 598,
 'entertainment': 599,
 'message': 600,
 'bring': 601,
 'appears': 602,
 'sister': 603,
 'whether': 604,
 'surprised': 605,
 'parents': 606,
 'hate': 607,
 'supporting': 608,
 'release': 609,
 'suspense': 610,
 'bunch': 611,
 'sequel': 612,
 'clear': 613,
 'dialog': 614,
 'romantic': 615,
 'certain': 616,
 'rock': 617,
 'giving': 618,
 'within': 619,
 'theme': 620,
 'theater': 621,
 'mention': 622,
 'using': 623,
 'buy': 624,
 'tale': 625,
 'needs': 626,
 'dull': 627,
 'easy': 628,
 'showing': 629,
 'working': 630,
 'ways': 631,
 'oscar': 632,
 'sorry': 633,
 'named': 634,
 'effort': 635,
 'monster': 636,
 'dog': 637,
 'among': 638,
 'stand': 639,
 'check': 640,
 'mystery': 641,
 'minute': 642,
 'nearly': 643,
 'greatest': 644,
 'fall': 645,
 'storyline': 646,
 'th': 647,
 'typical': 648,
 'stay': 649,
 'richard': 650,
 'doubt': 651,
 'gone': 652,
 'feels': 653,
 'subject': 654,
 'feature': 655,
 'dr': 656,
 'lady': 657,
 'red': 658,
 'avoid': 659,
 'actual': 660,
 'comments': 661,
 'general': 662,
 'move': 663,
 'famous': 664,
 'tried': 665,
 'fantastic': 666,
 'editing': 667,
 'deal': 668,
 'material': 669,
 'crime': 670,
 'realistic': 671,
 'follow': 672,
 'form': 673,
 'points': 674,
 'killing': 675,
 'rent': 676,
 'elements': 677,
 'tom': 678,
 'kept': 679,
 'viewing': 680,
 'period': 681,
 'viewers': 682,
 'okay': 683,
 'somehow': 684,
 'imagine': 685,
 'means': 686,
 'paul': 687,
 'leads': 688,
 'peter': 689,
 'premise': 690,
 'animation': 691,
 'brought': 692,
 'weak': 693,
 'believable': 694,
 'surprise': 695,
 'deep': 696,
 'figure': 697,
 'expected': 698,
 'imdb': 699,
 'crew': 700,
 'begins': 701,
 'average': 702,
 'hear': 703,
 'learn': 704,
 'dance': 705,
 'difficult': 706,
 'particular': 707,
 'wait': 708,
 'atmosphere': 709,
 'indeed': 710,
 'boys': 711,
 'open': 712,
 'situation': 713,
 'sit': 714,
 'doctor': 715,
 'eventually': 716,
 'free': 717,
 'romance': 718,
 'lame': 719,
 'sequences': 720,
 'shame': 721,
 'reviews': 722,
 'poorly': 723,
 'america': 724,
 'forget': 725,
 'decided': 726,
 'york': 727,
 'hot': 728,
 'note': 729,
 'whatever': 730,
 'fi': 731,
 'reading': 732,
 'sexual': 733,
 'sci': 734,
 'cop': 735,
 'truth': 736,
 'unless': 737,
 'society': 738,
 'meet': 739,
 'footage': 740,
 'de': 741,
 'write': 742,
 'third': 743,
 'box': 744,
 'cheesy': 745,
 'lee': 746,
 'leaves': 747,
 'perfectly': 748,
 'superb': 749,
 'credits': 750,
 'needed': 751,
 'meets': 752,
 'forced': 753,
 'beauty': 754,
 'gay': 755,
 'memorable': 756,
 'emotional': 757,
 'effect': 758,
 'became': 759,
 'begin': 760,
 'japanese': 761,
 'male': 762,
 'acted': 763,
 'features': 764,
 'stage': 765,
 'hands': 766,
 'laughs': 767,
 'nature': 768,
 'personal': 769,
 'otherwise': 770,
 'result': 771,
 'street': 772,
 'previous': 773,
 'joe': 774,
 'girlfriend': 775,
 'interested': 776,
 'season': 777,
 'sounds': 778,
 'comment': 779,
 'writers': 780,
 'air': 781,
 'question': 782,
 'nor': 783,
 'possibly': 784,
 'screenplay': 785,
 'western': 786,
 'crazy': 787,
 'weird': 788,
 'inside': 789,
 'total': 790,
 'pay': 791,
 'earlier': 792,
 'mess': 793,
 'plus': 794,
 'quickly': 795,
 'c': 796,
 'badly': 797,
 'background': 798,
 'island': 799,
 'battle': 800,
 'setting': 801,
 'forward': 802,
 'following': 803,
 'development': 804,
 'fire': 805,
 'towards': 806,
 'front': 807,
 'directors': 808,
 'masterpiece': 809,
 'powerful': 810,
 'baby': 811,
 'keeps': 812,
 'worked': 813,
 'dumb': 814,
 'brings': 815,
 'creepy': 816,
 'business': 817,
 'copy': 818,
 'apart': 819,
 'ask': 820,
 'dramatic': 821,
 'match': 822,
 'william': 823,
 'directing': 824,
 'mark': 825,
 'zombie': 826,
 'dream': 827,
 'rate': 828,
 'bill': 829,
 'incredibly': 830,
 'admit': 831,
 'unique': 832,
 'rich': 833,
 'disney': 834,
 'appear': 835,
 'fighting': 836,
 'various': 837,
 'present': 838,
 'plenty': 839,
 'fails': 840,
 'water': 841,
 'fairly': 842,
 'leading': 843,
 'meant': 844,
 'political': 845,
 'caught': 846,
 'portrayed': 847,
 'reasons': 848,
 'joke': 849,
 'party': 850,
 'spent': 851,
 'telling': 852,
 'talented': 853,
 'era': 854,
 'realize': 855,
 'success': 856,
 'ideas': 857,
 'cover': 858,
 'twist': 859,
 'older': 860,
 'create': 861,
 'unlike': 862,
 'deserves': 863,
 'wasted': 864,
 'villain': 865,
 'break': 866,
 'odd': 867,
 'expecting': 868,
 'list': 869,
 'attempts': 870,
 'fantasy': 871,
 'cute': 872,
 'plain': 873,
 'clever': 874,
 'large': 875,
 'manages': 876,
 'co': 877,
 'ended': 878,
 'office': 879,
 'gun': 880,
 'escape': 881,
 'outside': 882,
 'casting': 883,
 'van': 884,
 'missed': 885,
 'flat': 886,
 'members': 887,
 'spoilers': 888,
 'hardly': 889,
 'century': 890,
 'return': 891,
 'agree': 892,
 'created': 893,
 'familiar': 894,
 'laughing': 895,
 'public': 896,
 'secret': 897,
 'recently': 898,
 'waiting': 899,
 'married': 900,
 'filmmakers': 901,
 'scott': 902,
 'company': 903,
 'missing': 904,
 'wrote': 905,
 'italian': 906,
 'pace': 907,
 'nudity': 908,
 'potential': 909,
 'remake': 910,
 'store': 911,
 'visual': 912,
 'incredible': 913,
 'train': 914,
 'science': 915,
 'german': 916,
 'considering': 917,
 'cause': 918,
 'pure': 919,
 'uses': 920,
 'filled': 921,
 'produced': 922,
 'cold': 923,
 'speak': 924,
 'state': 925,
 'suddenly': 926,
 'popular': 927,
 'mentioned': 928,
 'hair': 929,
 'hold': 930,
 'sadly': 931,
 'trouble': 932,
 'slightly': 933,
 'died': 934,
 'convincing': 935,
 'cartoon': 936,
 'anti': 937,
 'credit': 938,
 'brain': 939,
 'intelligent': 940,
 'sees': 941,
 'mad': 942,
 'sweet': 943,
 'former': 944,
 'language': 945,
 'value': 946,
 'tension': 947,
 'force': 948,
 'portrayal': 949,
 'kills': 950,
 'bored': 951,
 'la': 952,
 'decides': 953,
 'choice': 954,
 'dancing': 955,
 'moves': 956,
 'amount': 957,
 'f': 958,
 'band': 959,
 'amusing': 960,
 'g': 961,
 'pointless': 962,
 'alive': 963,
 'violent': 964,
 'fit': 965,
 'control': 966,
 'situations': 967,
 'neither': 968,
 'yeah': 969,
 'road': 970,
 'u': 971,
 'recommended': 972,
 'compared': 973,
 'fear': 974,
 'gang': 975,
 'respect': 976,
 'brothers': 977,
 'fiction': 978,
 'drug': 979,
 'project': 980,
 'biggest': 981,
 'meaning': 982,
 'master': 983,
 'studio': 984,
 'christmas': 985,
 'follows': 986,
 'images': 987,
 'common': 988,
 'jane': 989,
 'vampire': 990,
 'spirit': 991,
 'entirely': 992,
 'social': 993,
 'fake': 994,
 'successful': 995,
 'concept': 996,
 'law': 997,
 'depth': 998,
 'effective': 999,
 'focus': 1000,
 ...}

### Final labels

In [73]:
y_train = np.array(y_train)
y_val = np.array(y_val)
y_test = np.array(y_test)

In [74]:
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(34705,)
(7439,)
(7438,)

In [75]:
import pickle
with open("../models/tokenizer.pkl", "wb") as file:
    pickle.dump(tokenizer, file)

In [76]:
import numpy as np
np.save("../models/X_train_padded.npy", X_train_padded)
np.save("../models/X_val_padded.npy", X_val_padded)
np.save("../models/X_test_padded.npy", X_test_padded)
np.save("../models/y_train.npy", y_train)
np.save("../models/y_val.npy", y_val)
np.save("../models/y_test.npy", y_test)

In [77]:
X_train.to_pickle("../models/X_train_text.pkl")
X_val.to_pickle("../models/X_val_text.pkl")
X_test.to_pickle("../models/X_test_text.pkl")