# Dataset Preprocessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("../Datasets/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [3]:
data.shape

(7043, 21)

In [4]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
customer_ids = data["customerID"].copy()

In [6]:
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
data["TotalCharges"].astype(str).str.strip().eq("").sum()

np.int64(11)

In [8]:
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"],errors="coerce")

In [9]:
data["TotalCharges"].isnull().sum()

np.int64(11)

In [10]:
data.loc[data["TotalCharges"].isnull(),["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]]

      customerID  tenure  MonthlyCharges  TotalCharges Churn
488   4472-LVYGI       0           52.55           NaN    No
753   3115-CZMZD       0           20.25           NaN    No
936   5709-LVOEQ       0           80.85           NaN    No
1082  4367-NUYAO       0           25.75           NaN    No
1340  1371-DWPAZ       0           56.05           NaN    No
3331  7644-OMVMY       0           19.85           NaN    No
3826  3213-VVOLG       0           25.35           NaN    No
4380  2520-SGTTA       0           20.00           NaN    No
5218  2923-ARZLG       0           19.70           NaN    No
6670  4075-WKNIU       0           73.35           NaN    No
6754  2775-SEFEE       0           61.90           NaN    No

In [11]:
data.loc[data["TotalCharges"].isnull(), "TotalCharges"] = 0

In [12]:
data["TotalCharges"].isnull().sum()

np.int64(0)

In [13]:
data.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

In [14]:
data["customerID"].nunique()

7043

In [15]:
data = data.drop(columns=["customerID"])

In [16]:
data.shape

(7043, 20)

#### Split the dataset x and y

In [17]:
X = data.drop(columns=["Churn"])
y = data["Churn"]

In [18]:
print("X shape:",X.shape)
print("y shape:",y.shape)

X shape: (7043, 19)
y shape: (7043,)

In [19]:
y.value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [20]:
y.value_counts(normalize=True) * 100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

#### the target column is imbalanced.

#### Train/Test Split

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)

In [22]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (5634, 19)
X_test : (1409, 19)
y_train: (5634,)
y_test : (1409,)

In [24]:
import joblib
joblib.dump(X_train, "../models/X_train_raw.pkl")
joblib.dump(X_test, "../models/X_test_raw.pkl")

['../models/X_test_raw.pkl']

#### Numerical Features

In [25]:
numerical_features = [
    "SeniorCitizen",
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

#### Categorical Features

In [26]:
categorical_features = [
    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod"
]

In [27]:
print("Numerical features:")
print(numerical_features)
print("\nCategorical features:")
print(categorical_features)

Numerical features:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

Categorical features:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

In [28]:
print("Total features:", len(numerical_features) + len(categorical_features))
print("X_train columns:", X_train.shape[1])

Total features: 19
X_train columns: 19

#### One-hot encoding(categorical) and scaling(numerical)

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

#### Create the preprocessing transformer

In [33]:
preprocessor = ColumnTransformer(
    transformers=[("num",StandardScaler(),numerical_features),
                  ("cat",OneHotEncoder(handle_unknown="ignore",sparse_output=False),
                   categorical_features
                  )])

#### Fit only on training data

In [34]:
X_train_processed=preprocessor.fit_transform(X_train)
X_test_processed=preprocessor.transform(X_test)

In [35]:
print("X_train original shape:", X_train.shape)
print("X_train processed shape:", X_train_processed.shape)
print("X_test original shape:", X_test.shape)
print("X_test processed shape:", X_test_processed.shape)

X_train original shape: (5634, 19)
X_train processed shape: (5634, 45)
X_test original shape: (1409, 19)
X_test processed shape: (1409, 45)

In [36]:
print(type(X_train_processed))
print(type(X_test_processed))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

#### Check and handle outliers

In [37]:
numerical_features = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

In [38]:
for col in ["tenure", "MonthlyCharges", "TotalCharges"]:
    Q1=X_train[col].quantile(0.25)
    Q3=X_train[col].quantile(0.75)
    IQR=Q3-Q1
    lower_bound=Q1-1.5*IQR
    upper_bound=Q3+1.5*IQR
    outliers=X_train[(X_train[col]<lower_bound)|(X_train[col]>upper_bound)]
    print(f"{col}")
    print("Lower bound:", lower_bound)
    print("Upper bound:", upper_bound)
    print("Outlier count:", len(outliers))
    print()

tenure
Lower bound: -60.0
Upper bound: 124.0
Outlier count: 0

MonthlyCharges
Lower bound: -45.84374999999999
Upper bound: 171.50625
Outlier count: 0

TotalCharges
Lower bound: -4746.3
Upper bound: 8985.1
Outlier count: 0

#### No outliers in the datasets

In [39]:
print("Negative tenure:", (X_train["tenure"] < 0).sum())
print("Negative MonthlyCharges:", (X_train["MonthlyCharges"] < 0).sum())
print("Negative TotalCharges:", (X_train["TotalCharges"] < 0).sum())

Negative tenure: 0
Negative MonthlyCharges: 0
Negative TotalCharges: 0

#### Check class imbalance

In [40]:
print(y_train.value_counts())

Churn
No     4139
Yes    1495
Name: count, dtype: int64

In [41]:
print(y_train.value_counts(normalize=True) * 100)

Churn
No     73.464679
Yes    26.535321
Name: proportion, dtype: float64

In [42]:
import joblib
joblib.dump(preprocessor, "../models/preprocessor.pkl")
joblib.dump(X_train_processed, "../models/X_train_processed.pkl")
joblib.dump(X_test_processed, "../models/X_test_processed.pkl")
joblib.dump(y_train, "../models/y_train.pkl")
joblib.dump(y_test, "../models/y_test.pkl")

['../models/y_test.pkl']