# NLP Processing

In [27]:
import pandas as pd

In [28]:
data=pd.read_csv("../Datasets/customer_support_tickets.csv")

In [29]:
data.shape

(8469, 17)

In [30]:
print("Columns:")
print(data.columns.tolist())

Columns:
['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age', 'Customer Gender', 'Product Purchased', 'Date of Purchase', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority', 'Ticket Channel', 'First Response Time', 'Time to Resolution', 'Customer Satisfaction Rating']

In [31]:
data.dtypes

Ticket ID                         int64
Customer Name                       str
Customer Email                      str
Customer Age                      int64
Customer Gender                     str
Product Purchased                   str
Date of Purchase                    str
Ticket Type                         str
Ticket Subject                      str
Ticket Description                  str
Ticket Status                       str
Resolution                          str
Ticket Priority                     str
Ticket Channel                      str
First Response Time                 str
Time to Resolution                  str
Customer Satisfaction Rating    float64
dtype: object

In [32]:
data.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [33]:
missing_values=data.isnull().sum()
print("Missing Values",missing_values)

Missing Values Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                      5700
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

In [34]:
duplicates=data.duplicated().sum()
print("Duplicate values:",duplicates)

Duplicate values: 0

#### Select The Text Columns

In [35]:
data["Text"] = (data["Ticket Subject"].fillna("")+ " "+ 
                data["Ticket Description"].fillna(""))

In [36]:
data[["Ticket Subject", "Ticket Description", "Text"]].head()

,Ticket Subject,Ticket Description,Text
0,Product setup,I'm having an issue with the {product_purchase...,Product setup I'm having an issue with the {pr...
1,Peripheral compatibility,I'm having an issue with the {product_purchase...,Peripheral compatibility I'm having an issue w...
2,Network problem,I'm facing a problem with my {product_purchase...,Network problem I'm facing a problem with my {...
3,Account access,I'm having an issue with the {product_purchase...,Account access I'm having an issue with the {p...
4,Data loss,I'm having an issue with the {product_purchase...,Data loss I'm having an issue with the {produc...

In [37]:
print(data["Ticket Type"].value_counts())

Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

In [38]:
print("Number of classes:", data["Ticket Type"].nunique())

Number of classes: 5

#### Text Statistics

In [39]:
#Number of characters
data["Text_Chars"] = data["Text"].str.len()

In [40]:
#Number of words
data["Text_Word_Count"] = (data["Text"].str.split().str.len())

In [41]:
print(data["Text_Chars"].describe())
print(data["Text_Word_Count"].describe())

count    8469.000000
mean      306.546818
std        43.809154
min       161.000000
25%       289.000000
50%       315.000000
75%       335.000000
max       414.000000
Name: Text_Chars, dtype: float64
count    8469.000000
mean       48.467352
std         8.461730
min        23.000000
25%        45.000000
50%        51.000000
75%        54.000000
max        65.000000
Name: Text_Word_Count, dtype: float64

#### Clean the text

In [42]:
import re
def clean_text(text):
    text = str(text).lower()
    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)
    # Keep letters, spaces, and apostrophes
    text = re.sub(r"[^a-z\s']", " ", text)
    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [43]:
data["Clean_Text"] = data["Text"].apply(clean_text)

In [44]:
print(data["Clean_Text"].iloc[0])

product setup i'm having an issue with the product purchased please assist your billing zip code is we appreciate that you have requested a website address please double check your email address i've tried troubleshooting steps mentioned in the user manual but the issue persists

In [48]:
data[["Text", "Clean_Text"]].head()

,Text,Clean_Text
0,Product setup I'm having an issue with the {pr...,product setup i'm having an issue with the pro...
1,Peripheral compatibility I'm having an issue w...,peripheral compatibility i'm having an issue w...
2,Network problem I'm facing a problem with my {...,network problem i'm facing a problem with my p...
3,Account access I'm having an issue with the {p...,account access i'm having an issue with the pr...
4,Data loss I'm having an issue with the {produc...,data loss i'm having an issue with the product...

Tokenization

In [49]:
data["Tokens"] = data["Clean_Text"].str.split()

In [50]:
print(data["Tokens"].iloc[0])

['product', 'setup', "i'm", 'having', 'an', 'issue', 'with', 'the', 'product', 'purchased', 'please', 'assist', 'your', 'billing', 'zip', 'code', 'is', 'we', 'appreciate', 'that', 'you', 'have', 'requested', 'a', 'website', 'address', 'please', 'double', 'check', 'your', 'email', 'address', "i've", 'tried', 'troubleshooting', 'steps', 'mentioned', 'in', 'the', 'user', 'manual', 'but', 'the', 'issue', 'persists']

#### Stop-word handling

In [51]:
import nltk
from nltk.corpus import stopwords
nltk.download("stopwords")
stop_words = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [52]:
data["Tokens_No_Stopwords"] = data["Tokens"].apply(
    lambda tokens: [
        word for word in tokens
        if word not in stop_words
    ]
)

In [53]:
print(data["Tokens_No_Stopwords"].iloc[0])

['product', 'setup', 'issue', 'product', 'purchased', 'please', 'assist', 'billing', 'zip', 'code', 'appreciate', 'requested', 'website', 'address', 'please', 'double', 'check', 'email', 'address', 'tried', 'troubleshooting', 'steps', 'mentioned', 'user', 'manual', 'issue', 'persists']

#### Word frequency

In [54]:
from collections import Counter
all_words = [
    word
    for tokens in data["Tokens_No_Stopwords"]
    for word in tokens
]
word_counts = Counter(all_words)
word_frequency = pd.DataFrame(word_counts.most_common(20),columns=["Word", "Frequency"])
word_frequency

         Word  Frequency
0     product      18537
1   purchased      14444
2       issue      13083
3      please       8814
4      assist       6258
5     problem       3385
6        data       2158
7    software       2128
8     account       1972
9     support       1500
10      steps       1390
11      error       1320
12    noticed       1208
13   persists       1178
14       help       1177
15   hardware       1176
16    resolve       1165
17    request       1160
18     update       1157
19    message       1134

#### Bigram analysis

In [57]:
from sklearn.feature_extraction.text import CountVectorizer
bigram_vectorizer = CountVectorizer(
    ngram_range=(2, 2),
    stop_words="english",
    token_pattern=r"(?u)\b[a-zA-Z']+\b"
)
bigram_matrix = bigram_vectorizer.fit_transform(data["Clean_Text"])
bigram_counts = pd.DataFrame({
    "Bigram": bigram_vectorizer.get_feature_names_out(),
    "Frequency": bigram_matrix.sum(axis=0).A1
}).sort_values("Frequency",ascending=False)
bigram_counts.head(20)

                  Bigram  Frequency
26528  product purchased      14254
17144      issue product       6437
15334         i'm having       6346
14477       having issue       6175
27631   purchased assist       6108
17048          issue i'm       1785
15472       i've noticed       1190
17129     issue persists       1176
27772    purchased issue        995
11434      error message        972
15518         i've tried        966
33157       software bug        942
25770        problem i'm        892
7003   compatibility i'm        862
15408         i'm unable        853
8775           data loss        852
15315         i'm facing        836
3889        battery life        831
29754        request i'm        814
15426       i've checked        748

#### Trigram Analysis

In [58]:
trigram_vectorizer = CountVectorizer(
    ngram_range=(3, 3),
    stop_words="english",
    token_pattern=r"(?u)\b[a-zA-Z']+\b"
)
trigram_matrix = trigram_vectorizer.fit_transform(data["Clean_Text"])
trigram_counts = pd.DataFrame({
    "Trigram": trigram_vectorizer.get_feature_names_out(),
    "Frequency": trigram_matrix.sum(axis=0).A1
}).sort_values("Frequency",ascending=False)
trigram_counts.head(20)

                         Trigram  Frequency
26392    issue product purchased       6353
23509           i'm having issue       6151
22128       having issue product       6115
40263   product purchased assist       6106
26151           issue i'm having       1120
40373    product purchased issue        993
38415         problem i'm having        780
11904   compatibility i'm having        780
46387         request i'm having        729
40479   product purchased screen        641
43070   purchased assist product        638
26150           issue i'm facing        559
40242  product purchased account        542
46674    reset product purchased        503
57343  updates product purchased        503
50932   software updates product        502
18780      factory reset product        502
40360   product purchased hoping        502
36693    performed factory reset        502
38347        problem didn't help        502

In [59]:
X = data["Clean_Text"]
y = data["Ticket Type"]

In [60]:
print(y.value_counts())
print("\nNumber of classes:", y.nunique())

Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

Number of classes: 5

#### Train/Test Split

In [61]:
from sklearn.model_selection import train_test_split
X_train_text, X_test_text, y_train_text, y_test_text = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [62]:
print("Training samples:", len(X_train_text))
print("Testing samples :", len(X_test_text))

Training samples: 6775
Testing samples : 1694

In [63]:
print("\nTraining target distribution:")
print(y_train_text.value_counts())

Training target distribution:
Ticket Type
Refund request          1401
Technical issue         1398
Cancellation request    1356
Product inquiry         1313
Billing inquiry         1307
Name: count, dtype: int64

#### Create TF-IDF

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words="english",ngram_range=(1, 2),max_features=20000)

#### Fit TF-IDF only on training text

In [65]:
X_train_tfidf = tfidf.fit_transform(X_train_text)
X_test_tfidf = tfidf.transform(X_test_text)

#### Check the TF-IDF matrix

In [66]:
print("X_train TF-IDF shape:", X_train_tfidf.shape)
print("X_test TF-IDF shape :", X_test_tfidf.shape)

X_train TF-IDF shape: (6775, 20000)
X_test TF-IDF shape : (1694, 20000)

#### Inspect TF-IDF vocabulary

In [67]:
print("Number of vocabulary terms:",len(tfidf.vocabulary_))

Number of vocabulary terms: 20000

In [68]:
feature_names = tfidf.get_feature_names_out()
print(feature_names[:20])

['aaron arth' 'ab' 'ab ad' 'ability' 'ability customers' 'ability offer'
 'ability purchase' 'ability select' 'able' 'able accept'
 'able accomplish' 'able add' 'able additional' 'able address'
 'able afford' 'able answer' 'able concerned' 'able contact' 'able fix'
 'able help']

## Traditional NLP Model

#### 1.Logistic Expression

In [79]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
import time
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

In [70]:
text_lr = LogisticRegression(max_iter=1000,random_state=42)

In [71]:
start_time = time.time()
text_lr.fit(X_train_tfidf,y_train_text)
training_time = time.time() - start_time
print("Training time:", training_time)

Training time: 2.1303341388702393

In [73]:
y_pred_text_lr = text_lr.predict(X_test_tfidf)
y_proba_text_lr = text_lr.predict_proba(X_test_tfidf)

#### Evaluate the metrics

In [75]:
text_lr_accuracy = accuracy_score(y_test_text,y_pred_text_lr)
text_lr_precision = precision_score(y_test_text,y_pred_text_lr,average="weighted",zero_division=0)
text_lr_recall = recall_score(y_test_text,y_pred_text_lr,average="weighted",zero_division=0)
text_lr_f1 = f1_score(y_test_text,y_pred_text_lr,average="weighted",zero_division=0)

In [76]:
nlp_results = []
nlp_results.append({
    "Model": "TF-IDF + Logistic Regression",
    "Accuracy": text_lr_accuracy,
    "Precision": text_lr_precision,
    "Recall": text_lr_recall,
    "F1-Score": text_lr_f1,
    "Training Time (sec)": training_time
})

In [77]:
nlp_results

[{'Model': 'TF-IDF + Logistic Regression',
  'Accuracy': 0.2154663518299882,
  'Precision': 0.21556791408332704,
  'Recall': 0.2154663518299882,
  'F1-Score': 0.21527299390855342,
  'Training Time (sec)': 2.1303341388702393}]

In [78]:
nlp_results_df = pd.DataFrame(nlp_results).round(4)
nlp_results_df

,Model,Accuracy,Precision,Recall,F1-Score,Training Time (sec)
0,TF-IDF + Logistic Regression,0.2155,0.2156,0.2155,0.2153,2.1303

#### 2.Naive_Bayes

In [80]:
text_nb = MultinomialNB()

In [81]:
start_time = time.time()
text_nb.fit(X_train_tfidf,y_train_text)
training_time = time.time() - start_time
print("Training time:", training_time)

Training time: 0.048894405364990234

In [82]:
y_pred_text_nb = text_nb.predict(X_test_tfidf)

#### Evaluate the metrics

In [83]:
text_nb_accuracy = accuracy_score(y_test_text,y_pred_text_nb)
text_nb_precision = precision_score(y_test_text,y_pred_text_nb,average="weighted",zero_division=0)
text_nb_recall = recall_score(y_test_text,y_pred_text_nb,average="weighted",zero_division=0)
text_nb_f1 = f1_score(y_test_text,y_pred_text_nb,average="weighted",zero_division=0)

In [84]:
nlp_results.append({
    "Model": "TF-IDF + Naive Bayes",
    "Accuracy": text_nb_accuracy,
    "Precision": text_nb_precision,
    "Recall": text_nb_recall,
    "F1-Score": text_nb_f1,
    "Training Time (sec)": training_time
})

In [85]:
nlp_results_df = pd.DataFrame(
    nlp_results
).round(4)

nlp_results_df

,Model,Accuracy,Precision,Recall,F1-Score,Training Time (sec)
0,TF-IDF + Logistic Regression,0.2155,0.2156,0.2155,0.2153,2.1303
1,TF-IDF + Naive Bayes,0.2149,0.2162,0.2149,0.2035,0.0489

In [86]:
nlp_results_df.to_csv("../models/phase14_traditional_nlp_results.csv",index=False)